name: shovon_resume
description: "Personal Details of Mahmudur Rahman Shovon, A Python and Flutter enthusiast."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.7.0
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/logo/

flutter_launcher_icons:
  # image_path: "assets/icon/icon.png"
  web:
    generate: true
    image_path: "assets/logo/s_logo.jpeg"
    background_color: "#FFFFFF"
    theme_color: "#694B08"
